# Configuration for the labeler action (v6 format)
# Labels to apply based on file changes

src:
  - any:
      changed-files:
        - any-glob-to-any-file: ['src/**/*']

documentation:
  - any:
      changed-files:
        - any-glob-to-any-file: ['*.md', 'docs/**/*']

configuration:
  - any:
      changed-files:
        - any-glob-to-any-file: ['*.yaml', '*.yml', 'config/**/*']

dependencies:
  - any:
      changed-files:
        - any-glob-to-any-file: ['requirements.txt', 'setup.py', 'pyproject.toml']

tests:
  - any:
      changed-files:
        - any-glob-to-any-file: ['tests/**/*', 'test_*']
